/*
 * BomIpcMsgDef.h
 *
 *  Created on: Dec 12, 2016
 *      Author: root
 */

#ifndef BOMIPCMSGDEF_H_
#define BOMIPCMSGDEF_H_

#include "ipcpublic.h"

typedef enum
{
	EM_IPCMSG_SYN_CORE_TO_UI =     0x9001,				//BOMCORE发给UI的同步消息
	EM_IPCMSG_ASYN_CORE_TO_UI =    0x9002,				//BOMCORE发给UI的异步消息
	EM_IPCMSG_DIALOG_CORE_TO_UI =  0x9003,				//BOMCORE发给UI的对话框显示消息
	EM_IPCMSG_SYN_UI_TO_CORE =     0x9004,				//UI发给BOMCORE的同步消息
	EM_IPCMSG_ASYN_UI_TO_CORE =    0x9005,				//UI发给BOMCORE的异步消息

}EM_BOM_IPCMSG_ID;

typedef enum
{
	MSG_PARAM_PRIV_SHUTDOWN =                         	4531,//关机
	MSG_PARAM_BUSINESS_END =                          	4532, //运营结束
	MSG_PARAM_PRIV_ReStart =                          	4533, //重启
	MSG_PARAM_PRIV_LOGIN =                          	4534, //登录
	MSG_PARAM_PRIV_LOGOUT =                          	4535, //登出

	MSG_PARAM_SETTIME = 								4561,//设置时间
	MSG_PARAM_SYNCTIME = 								4562,//时钟同步
	MSG_PARAM_SET_LOCAL_PARAM = 						4563,//本机参数设置
	MSG_PARAM_GET_LOCAL_IP = 							4564,//获得本机ip
	MSG_PARAM_SET_LOCAL_IP = 							4565,//设置本机ip
	MSG_PARAM_SET_SC_IP_PORT = 							4566, /*!<SC地址端口设置 */
	MSG_PARAM_SET_FTP = 								4567,//ftp

	MSG_PARAM_GET_FARE =                             	1001,/*获取票价*/

	MSG_PARAM_SHOW_DIALOG =                             1002,/*显示对话框*/
	MSG_PARAM_HIDE_DIALOG =                             1003,/*隐藏对话框*/
	MSG_PARAM_BOX_COUNT=                                1004,/*通知界面更新票箱信息*/
	MSG_PARAM_STATUS=                               	1005,/*状态*/
	MSG_PARAM_UIJUMP=                               	1006,/*界面跳转*/

	MSG_PARAM_DEV_INIT=                                 2001,/*设备初始化*/

	MSG_PARAM_SLETICKET_SINGLETICKET =              	4001,/*售单程票*/
	MSG_PARAM_PRINTL_SLETICKET_SINGLETICKET =        	4041,/*售单程票票据打印*/

	//查询读卡
	MSG_INNER_READCARD_QUERYCARD_AEAR = 				4187,/*查询读卡*/
	MSG_INNER_READCARD_QUERYCARD_QUERYHISTORYINFO  = 	4322,/*票卡历史记录查询*/
	MSG_INNER_READCARD_QUERYCARD_RETURNHISTORYINFO  = 	4321,/*票卡信息查询返回*/



	//补票读卡
	MSG_INNER_EXCESSFARE_PAIDAREA_READCARD  = 4387,/*付费区补票读卡*/
	MSG_INNER_EXCESSFARE_NONPAIDAREA_READCARD  = 4388,/*非付费区补票读卡*/

	//出站更新
	MSG_INNER_EXCESSFARE_EXIT_COMPENSATION  = 4301,/*出站更新*/
	MSG_INNER_EXCESSFARE_EXIT_COMPENSATION_PRINT  = 4341,/*出站更新打印*/


	//进站更新
	MSG_INNER_EXCESSFARE_ENTER_COMPENSATION  = 4302,/*进站更新*/
	MSG_INNER_EXCESSFARE_ENTER_COMPENSATION_PRINT  = 4342,/*进站更新打印*/

	//超时更新
	MSG_INNER_EXCESSFARE_TIMEOUT = 4303,/*超时更新*/
	MSG_INNER_EXCESSFARE_TIMEOUT_PRINT = 4343,/*超时更新打印*/

	//超程更新
	MSG_INNER_EXCESSFARE_OVERTRAVEL = 4304,/*超程更新*/
	MSG_INNER_EXCESSFARE_OVERTRAVEL_PRINT = 4344,/*超程更新打印*/

	//超时超程更新
	MSG_INNER_EXCESSFARE_TIMEOUTOVERTRAVEL = 4305,/*超时超程更新*/
	MSG_INNER_EXCESSFARE_TIMEOUTOVERTRAVEL_PRINT = 4345,/*超时超程更新打印*/

	//充值 或 发站距票价出站票并免费更新票卡次序为出站
	MSG_INNER_EXCESSFARE_ADDVALUES = 4306,/*充值*/
	MSG_INNER_EXCESSFARE_SALEEXITSTATIONTICKET = 4307,/*发售付费出站票*/
	MSG_INNER_EXCESSFARE_SALEFREEEXITSTATIONTICKET = 4308,/*发售免费出站票*/


	//付费区卡内支付
	MSG_INNER_EXCESSFARE_PAIDAREA_PAYMENT  = 4310,/*付费区支付方式*/

	//非付费区支付方式
	MSG_INNER_EXCESSFARE_NONPAIDAREA_PAYMENT  = 4312,/*非付费区支付方式*/


	//免费进站更新
	MSG_INNER_EXCESSFARE_FREE_ENTER_COMPENSATION  = 4313,/*免费进站更新*/

	MSG_INNER_EXCESSFARE_FREE_EXIT_COMPENSATION  = 4314,/*免费出站更新*/

	//退卡读卡
	MSG_INNER_WITHDRAW_READCARD  =4487,/*退卡读卡*/

	//UL卡退卡
	MSG_INNER_WITHDRAW_ULTICKET  =4401,/*一票通退卡*/
	MSG_INNER_PRINT_WITHDRAW_ULTICKET  =4441,/*一票通退卡打印*/

	//储值卡退卡
	MSG_INNER_WITHDRAW_STORECARD = 4402,/*储值卡退卡*/
	MSG_INNER_PRINT_WITHDRAW_STORECARD = 4442,/*储值卡退卡打印*/


	//切换付费区
	MSG_INNER_AWITCH_PAIDAREA = 4552,//切换付费区

	MSG_INNER_PRIV_LOGIN					    = 5001,  /*!<登录请求 */
	MSG_INNER_PRIV_CHANGE_PASSWORD         = 5102,  /*修改密码*/
	MSG_INNER_PRIV_LOG_OUT_MANUA           = 5103, //手工登出
	MSG_INNER_PRIV_LOG_OUT_AUTO            = 5104, //自动登出
	MSG_INNER_PRIV_LOG_OUT_FORCED          = 5105, //强制登出
	MSG_INNER_PRIV_LOG_OUT_SETTLEMENT      = 5106, //结算登出
	MSG_INNER_PRIV_LOG_OUT_RUN_END         = 5107, //运营结束登出
	MSG_INNER_PRIV_GET_PRINCE              = 5108, //计算票价
	MSG_INNER_PRIV_GET_DEPOSIT 			   = 5109, //计算押金

}EM_IPCMSG_PARAM;

typedef enum
{
	ADDITIONAL_OPERATION_NOOPERATION =             0x00,//无附加条件
	ADDITIONAL_OPERATION_CONFIRM =                 0x01,//确认
	ADDITIONAL_OPERATION_CANCEL =                  0x02,//取消
	ADDITIONAL_OPERATION_STOP =                    0x03,//停止
	ADDITIONAL_OPERATION_CONTINUE =                0x04,//继续
	ADDITIONAL_OPERATION_LOCK_SCREEN =             0x05,//锁屏
	ADDITIONAL_OPERATION_UNLOCK_SCREEN =           0x06,//解锁
	ADDITIONAL_OPERATION_CONFIRM_CANCEL =          0x07,//确认-取消
	ADDITIONAL_OPERATION_CONTINUE_STOP =           0x08,//继续-停止
	ADDITIONAL_OPERATION_RESET_CANCEL =            0x09,//错误重置-取消
	ADDITIONAL_OPERATION_CLOSE_DIALOG =            0x10,//取消对话框

//更新
	ADDITIONAL_OPERATION_FREE_ENTER_UPDATE=        0x20,//免费进站更新
	ADDITIONAL_OPERATION_MONEY_PAY_ENTER_UPDATE=     0x21,//付费进站更新
	ADDITIONAL_OPERATION_TIMESCOUNT_ENTER_UPDATE=     0x22,//计次票进站更新
	ADDITIONAL_OPERATION_MONEYORCARD_PAY_ENTER_UPDATE=     0x23,//付费进站更新
	ADDITIONAL_OPERATION_FREE_EXIT_UPDATE_SJT=        0x24,//免费出站更新
	ADDITIONAL_OPERATION_FREE_EXIT_UPDATE_SVN=        0x25,//免费出站更新
	ADDITIONAL_OPERATION_MONEY_PAY_EXIT_UPDATE=     0x26,//付费出站更新
	ADDITIONAL_OPERATION_TIMESCOUNT_EXIT_UPDATE=     0x27,//计次票出站更新
	ADDITIONAL_OPERATION_MONEYORCARD_PAY_EXIT_UPDATE=     0x28,//付费出站更新
	ADDITIONAL_OPERATION_MONEY_OVERTIME_UPDATE=     0x29,//超时更新
	ADDITIONAL_OPERATION_MONEYORCARD_OVERTIME_UPDATE=     0x30,//超时更新
	ADDITIONAL_OPERATION_OVERTRAVEL_UPDATE=     0x31,//超程更新
	ADDITIONAL_OPERATION_OVERTIME_AND_OVERTRAVEL_UPDATE=     0x32,//超时超程更新
	ADDITIONAL_OPERATION_ADDVALUE=     0x33,//充值


}EM_IPCMSG_ADDITIONAL_OPERATION;


typedef struct
{
	EM_IPCMSG_PARAM emIpcParam;
	EM_IPCMSG_ADDITIONAL_OPERATION emAdditinalOperation;
    int iAdditionalDataLen;
    char szAdditionalData[MAX_ADDITIONAL_DATE_LENGTH];
}ST_BOM_IPCMSG_INFO;


#endif /* BOMIPCMSGDEF_H_ */
